# Week 3 Lect 1 - Indexing


## Boolean Indexing

In [14]:
import numpy as np

X = np.array([1,2,3,4,5,6]).reshape(-1,2)
M = X >= 3
M

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [3]:
X[M] # Can be used as a selector! But the shape of the array is lost.

array([3, 4, 5, 6])

In [4]:
X[X>=5] = -1 # This is a thing I guess.
X

array([[ 1,  2],
       [ 3,  4],
       [-1, -1]])

In [5]:
A = np.arange(20).reshape(4,5)
B = np.arange(20,40).reshape(4,5)
B[A%2==0] # As long as the indeces matrix has the same shape as the matrix at hand.

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

## Indexing with an int array

In [6]:
X = np.arange(20).reshape(4,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
ids = [1,3]
X[ids]  # Straightforward.

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [8]:
# You can also do this
print(X[ids,ids])
print(X[(ids,ids)])
print(X[(ids,ids),(ids,ids)])
print(X[ids][1])

[ 6 18]
[ 6 18]
[[ 6 18]
 [ 6 18]]
[15 16 17 18 19]


## Function 'where'
Return elements chosen from x or y depending on condition.



In [9]:
X = np.arange(10)
np.where(X>3)

(array([4, 5, 6, 7, 8, 9]),)

## Stacking arrays, array manipulation
Arrays can stack vertically `vstack` or horizontally `hstack`. 

Arrays can be stuck together along different axis.

In [10]:
X = np.arange(10).reshape(2,-1)
Z = np.arange(10,20).reshape(2,-1)
print(X)
print(Z)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [11]:
hstck = np.hstack([X,Z])
hstck # You must have the same number of rows

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [12]:
vstck = np.vstack([X,Z])
vstck # You must have the same number of columns

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
X = np.arange(12).reshape(3,-1)
print(X.shape)
hsplt = np.hsplit(X,2)
print(np.array(hsplt).shape)
print(X)
print(np.array(hsplt))

(3, 4)
(2, 3, 2)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[ 2  3]
  [ 6  7]
  [10 11]]]


In [21]:
X = np.arange(12).reshape(3,-1)
print(X)
vsplt = np.vsplit(X,3)
vsplt


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

# Week 3 Lect 2 - Operations between arrays

## Addition & substraction

In [23]:
import numpy as np
X = np.arange(10).reshape(2,-1)
Y = np.arange(10,20).reshape(2,-1)
X+Y

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

## Broadcasting

Used to handle arrays of different shapes. There are still certain restrictions to this. There are a couple of rules:

1. 

2.

3.

4.
