In [1]:
import numpy as np

# Practice

## Question 1

Write a function `make_matrix(n_rows, n_cols)` that creates a `n_rows` x `n_cols` array with increasing entries starting from 1. The entries must be float numbers.

Write two functions:`m_min` and `m_max` to extract the min and the max entry in the array. 
You can use the `max` and `min` function provided by core python.


In [38]:
def make_matrix(n_rows, n_cols):
    flat = np.arange(1,n_rows*n_cols+1, dtype=float)
    return flat.reshape(n_rows,n_cols)


In [39]:
def m_min(A):
    return np.sort(np.ravel(A))[0]

In [40]:
def m_max(A):
    return np.sort(np.ravel(A))[::-1][0]

In [58]:
X = make_matrix(2,3)
m_max(test)

15

## Test question 1

Your code should not raise any error.

In [42]:
A = make_matrix(n_rows=5, n_cols=5)
print(A)
print(m_min(A), m_max(A))

assert A.dtype == 'float', 'Matrix must contain floats'

assert A.shape == (5,5), 'Matrix should be 5x5'

assert m_min(A) == 1, 'Min should be 1'

assert m_max(A) == 25, 'Max should be 25'

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]
1.0 25.0


## Question 2

Using the previous function `make_matrix` create a 5x5 matrix with entries 1 to 25. 

Using the max and the min function, write a function `scale(A)` to proportionally scale all array entries of an array `A` so that these are in the range $[0,1]$.

In [80]:
def normalise(value, lownew, highnew, low, high):
    return (value - low)/(high-low)

normalise(25, 0,1, 1,25)

1.0

In [85]:
def scale(A):
    nmin = m_min(A)
    nmax = m_max(A)
    processing = lambda x : normalise(x, 0, 1, 1, 25)
    return processing(A)


In [86]:
X = make_matrix(1,25)[0]
print(X)
X_norm = scale(X)
print(X_norm)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25.]
[0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333
 1.        ]


## Test question 2

Your code should not raise any error.

In [87]:
A = make_matrix(n_rows=5, n_cols=5)
B = scale(A)
print(B)

assert B[0,0] == 0, 'B[0,0] should be 0'
assert B[1,1] == 0.25, 'B[1,1] should be 0.25'
assert B[4,4] == 1, 'B[4,4] should be 1'

[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


## Question 3

Write a function `transpose(X)` that for a two dimensional numpy array outputs its transposed. When `B` is the transposed of `A`, then `B[i,j]=A[j,i]`. 

In your function use the `assert` statement to ensure that the array in input is two dimensional.

Write a function `transpose_square(X)` that for a square two dimensional numpy array outputs its transposed. This function must operate **in place** that is, it should not allocate any extra memory.

In your function use the `assert` statement to ensure that the array in input is square.

In [169]:
def transpose(X):
    flat = np.ravel(X)
    t_transpose = np.zeros((X.shape[1], X.shape[0]))

    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            t_transpose[j,i] = X[i,j]
    return t_transpose
    
def transpose_square(X):
    if X.shape[0] != X.shape[1]:
        raise Exception()
    for i in range(X.shape[0]):
        for j in range(i+1,X.shape[1]):
            temp = X[i][j] 
            X[i][j] = X[j][i]
            X[j][i] = temp
    return X
    

In [170]:
X3 = make_matrix(4,4)
print(X3)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [171]:
transpose(X3)

array([[ 1.,  5.,  9., 13.],
       [ 2.,  6., 10., 14.],
       [ 3.,  7., 11., 15.],
       [ 4.,  8., 12., 16.]])

In [172]:
transpose_square(X3)

array([[ 1.,  5.,  9., 13.],
       [ 2.,  6., 10., 14.],
       [ 3.,  7., 11., 15.],
       [ 4.,  8., 12., 16.]])

## Test question 3

Your code should not raise any error.

In [173]:
X = np.arange(12).reshape(-1, 3)
print(X)
print(transpose(X))
assert np.all(transpose(X) == X.T), 'transpose(X) should yield the same result as X.T'

X = np.arange(12).reshape(-1, 2, 3)
try:
    B = transpose(X)
except Exception:
    pass
else:
    assert False, 'the function should raise an exception if the input is not a two dim array'
    
X = np.arange(9).reshape(-1, 3)
Xp = X.copy()
assert np.all(transpose_square(X) == Xp.T), 'transpose(X) should yield the same result as copy_of(X).T'

X = np.arange(12).reshape(-1, 3)
try:
    B = transpose_square(X)
except Exception:
    pass
else:
    assert False, 'the function should raise an exception if the input is not a square two dim array'

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0.  3.  6.  9.]
 [ 1.  4.  7. 10.]
 [ 2.  5.  8. 11.]]
