In [2]:
import numpy as np

# Practice

## Question 1

Write a function called `count_common(A,B)` to count, efficiently, how many elements share the same value at the same position in `A` and `B`.

Write a function called `find_common(A,B)` to find, efficiently, the position of the elements that share the same value at the same position in `A` and `B`. The function should return both the values that are in common and their positions.  

Throw an error if the arrays are not one dimensional. 

In [27]:
A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10)
print(A)
print(B)
A==B

[7 8 9 6 4 9 2 8 9 5]
[8 5 9 6 5 5 5 6 5 3]


array([False, False,  True,  True, False, False, False, False, False,
       False])

In [28]:
def count_common(A,B):
    return sum(A==B)

def find_common(A,B):
    indeces = [i for i, value in zip(range(len(A)), A==B) if value==True]
    return (indeces, A[A==B])

In [29]:
print(find_common(A,B))
print(count_common)

([2, 3], array([9, 6]))
<function count_common at 0x1213c2a60>


## Test question 1

Your code should not raise any error.

In [30]:
A = np.arange(11)
B = A[::-1].copy()
print(A)
print(B)
out = count_common(A,B)

assert out == 1, 'the function should return 1'

out = find_common(A,B)
assert len(out) == 2, 'the function should return two values'
vals, ids = out
assert np.all(vals == [5]), 'the function should return 5'
assert np.all(ids == [5]), 'the function should return 5'

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


## Question 2

Cerate a function `cutoff(A, lower, upper)` replace all values greater than `upper` with `upper` and those less than `lower` with `lower`.

In [37]:
A = np.random.randint(0,10,10)
A[A>4] = -1
A

array([-1,  4,  0,  2,  3,  3, -1, -1,  4, -1])

In [38]:
def cutoff(A, lower, upper):
    A[A>upper] = upper
    A[A<lower] = lower
    return A

## Test question 2

Your code should not raise any error.

In [39]:
A = np.arange(25).reshape(5, 5)
print(A)
B = cutoff(A, 5, 10)
print(B)
assert np.all(B[0] == [5]*5), 'the function should return a first row of 5s'
assert np.all(B[-1] == [10]*5), 'the function should return a last row of 10s'

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  5  5  5  5]
 [ 5  6  7  8  9]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


## Question 3

Create a function `rank(A)` that outputs the ranks of the values of the one dimensional input array `A`.

```
Ex:
array:  [0.3 2.3 4.3 0.7 2.7 4.7]
indeces: [0 3 1 4 2 5]
ranks:  [0 2 4 1 3 5]
which would be: [0.3 4.3 2.4 2.3 0.7 4.7]
```

In [65]:
def rank(A):
    assert A.ndim == 1, "The array needs to be one dimensional"
    indeces = np.argsort(A)
    ranks = np.zeros_like(indeces)
    for counter, index in zip(range(len(indeces)), indeces):
        ranks[index] = counter
    return ranks


rank(np.random.randint(0,10,6))

array([1, 0, 2, 5, 3, 4])

## Test question 3

Your code should not raise any error.

In [66]:
A = np.arange(6)[::2]+0.3
B = np.arange(1,6)[::2]-0.3
C = np.hstack([A,B])
print(C)
out = rank(C)
print(out)

assert np.all(out == [0,2,4,1,3,5]), 'the function should return [0 2 4 1 3 5]'

[0.3 2.3 4.3 0.7 2.7 4.7]
[0 2 4 1 3 5]
