In [2]:
import numpy as np

ARRAY CREATION

`np.random.uniform(low=0.0, high=1.0, size=None)`

`np.random.randint(low, high=None, size=None, dtype=int)`

`np.random.randint(size=None)`

`np.random.randint(size=None)`

`np.arange(start, stop, step, dtype=None)`

`np.arange(size=None, dtype=None)`

`np.zeros(size=None, dtype=None)`

`np.identity(n, dtype=None, *, like=None)` => The identity array is a square array with ones on the main diagonal.

`np.fromstring(string, dtype=float, count=- 1, sep='', *, like=None)`








RESHAPING AND FLATTENING

`np.reshape(list, newshape)`

`np.ravel(list, order='C')`

`np.vsplit(list, indices_or_sections)`

`np.hsplit(list, indices_or_sections)`

`np.vstack(tuple)`

`np.hstack(tuple)`






SORTING


`np.sort(a, axis=- 1, kind=None, order=None)`

`np.argsort(a, axis=- 1, kind=None, order=None)`

`np.argmax(a, axis=None, out=None)`

`np.argmin(a, axis=None, out=None)`

`np.nanargmax(a, axis=None)`

`np.nanargmax(a, axis=None)`

INDEXING

`np.where(Bool array)` => returns indices!

`np.choice(a, size=None, replace=True, p=None)`




# Array creation

In [35]:
np.fromstring('1 2', dtype=int, sep=' ')

array([1, 2])

In [6]:
# min, max, size
np.random.uniform(0,1,(2,2))

array([[0.36131962, 0.37486579],
       [0.92417871, 0.18289782]])

In [11]:
np.random.randint(0,2,(2,2))

array([[1, 1],
       [0, 0]])

In [30]:
np.random.rand(3) # Between 0 and 1

array([0.2881252 , 0.58180614, 0.7733555 ])

In [34]:
np.arange(0,10,2, dtype=int)

array([0, 2, 4, 6, 8])

In [21]:
np.ones((3,2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [26]:
np.zeros(4, dtype=int)

array([0, 0, 0, 0])

An identity array is a square array with ones on its main diagonal

`identity(n, dtype=None)`

In [27]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Reshaping and flattening

In [13]:
np.arange(6).reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
np.arange(6).reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
X = np.arange(6).reshape(2,-1)
X.flatten()

array([0, 1, 2, 3, 4, 5])

In [17]:
np.ravel(X)

array([0, 1, 2, 3, 4, 5])

In [18]:
X.reshape(6,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Splitting and joining arrays V + H

In [31]:
X = np.arange(10).reshape(2,-1)
Z = (np.arange(10)+20).reshape(2,-1)
print(X)
print('-'*20)
print(Z)

[[0 1 2 3 4]
 [5 6 7 8 9]]
--------------------
[[20 21 22 23 24]
 [25 26 27 28 29]]


In [32]:
np.hstack([X,Z])

array([[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29]])

In [33]:
np.vstack([X,Z])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [34]:
X = np.arange(12).reshape(2,-1)
print(X)
L = np.hsplit(X,3) # split in 3
L

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

In [35]:
L = np.hsplit(X,(3,4))   # split a after the third and the fourth column
L

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[3],
        [9]]),
 array([[ 4,  5],
        [10, 11]])]

# Sorting

In [44]:
X = np.random.randint(0,10,9).reshape(3,-1)
X

array([[2, 3, 1],
       [3, 7, 8],
       [1, 9, 6]])

In [48]:
np.sort(X, axis=0)

array([[1, 3, 1],
       [2, 7, 6],
       [3, 9, 8]])

In [49]:
np.argsort(X, axis=0) #Returns the indices that would sort an array

array([[2, 0, 0],
       [0, 1, 2],
       [1, 2, 1]])

In [50]:
np.argmax(X)

7

If you give `argmax` a multi dimensional array, it will return the maximum value along the flattened array or along an axis.

In [72]:
X = np.random.randint(0,20,10).reshape(5,-1)
print(X)
print(X.reshape(-1))
print("You can print the index of the flattened array: %s"% np.argmax(X))
print("Or the index when axis=0: %s"%np.argmax(X, axis=0))
print("Or the index when axis=1: %s"%np.argmax(X, axis=1))



[[12 13]
 [ 6 11]
 [16  7]
 [13 19]
 [ 1 14]]
[12 13  6 11 16  7 13 19  1 14]
You can print the index of the flattened array: 7
Or the index when axis=0: [2 3]
Or the index when axis=1: [1 1 0 1 1]


`nanargmax` returns the index of the maximum value without considering the NaN and Inf values. Alternatively, argmax will consider NaN values and select them.

In [58]:
a = np.array([[np.nan, 4], [2, 3]])
maxvalue = np.argmax(a)
print('Max value at row %s, value %s'% (maxvalue, a[maxvalue]))

Max value at row 0, value [nan  4.]


In [60]:
maxvalue = np.argmax(a, axis=0)
print(maxvalue, a[maxvalue[0], maxvalue[1]])



[0 0] nan


In [52]:
np.nanargmax(a) # Avoids NaN
1

1

In [53]:
np.nanargmax(a, axis=0)

array([1, 0])

# Multi-dimensional array operations

## Broadcasting


|#|what|
|---|:---|
| 1| all input arrays with ndim smaller than the input array of largest ndim, have 1’s *prepended* to their *shapes* |
| 2| the size in each dimension of the output shape is the *maximum* of all the input sizes in that dimension |
| 3| an input can be used in the calculation *if* its size in a particular dimension either
|  |  - matches the output size in that dimension|
|  | - or has value exactly 1 |
| 4| if an input has a dimension *size of 1* in its shape, the first data entry in that dimension will be used for all calculations along that dimension |


In [5]:
a = np.arange(5).reshape(5,1)
b = np.arange(6).reshape(1,6)

print(a, a.shape)
print(b, b.shape)

[[0]
 [1]
 [2]
 [3]
 [4]] (5, 1)
[[0 1 2 3 4 5]] (1, 6)


In [3]:
a*b

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5],
       [ 0,  2,  4,  6,  8, 10],
       [ 0,  3,  6,  9, 12, 15],
       [ 0,  4,  8, 12, 16, 20]])

In [15]:
a0 = np.hstack((a,a,a,a,a,a))
b0 = np.vstack((b,b,b,b,b))

print(a0)
print(b0)

[[0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]
 [4 4 4 4 4 4]]
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]


In [17]:
a0*b0 == a*b

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

# Indexing

BOOLEAN INDEXING

In [8]:
X = np.array([[0,1,2],[3,4,5]])
print(X)
print(X>=2)
X[X>=2] # Returns a flattened array

[[0 1 2]
 [3 4 5]]
[[False False  True]
 [ True  True  True]]


array([2, 3, 4, 5])

In [10]:
Y = X >= 2 # Compiler does Y = X, then Y >= 2 
Y

array([[False, False,  True],
       [ True,  True,  True]])

In [12]:
X[X>=2] = 9000
X

array([[   0,    1, 9000],
       [9000, 9000, 9000]])

In [15]:
ids = [1,3]
X.flatten()[ids]

array([   1, 9000])

In [18]:
X[:,0:2]

array([[   0,    1],
       [9000, 9000]])

In [20]:
X = np.arange(20).reshape(4,5)
print(X)
np.where(X>3) # Returns an array for each axis

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


(array([0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [13]:
def swap_rows(A, i=0, j=1):
    # this works in Python but not in NP! Because NP creates views of original data (rather than copying references)
    #A[i], A[j] = A[j], A[i]

    # this works because you are instructing NP to work on copies of rows rather than views
    #A[i], A[j] = A[j].copy(), A[i].copy()

    # this works because fancy indexing implicitly creates copies
    A[[i, j]] = A[[j, i]]
    
    # this swaps columns
    #A[:,[i, j]] = A[:,[j, i]]

A = np.arange(1, 26).reshape(5, 5)
swap_rows(A, i=0, j=1)
print(A)

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# Other

# Other